#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'ruby_build',
  :git => 'git://github.com/fnichol/chef-ruby_build.git', :ref => 'v0.6.0'
cookbook 'rbenv',
  :git => 'https://github.com/fnichol/chef-rbenv', :ref => 'v0.6.4'
cookbook 'apt',
  :git => 'https://github.com/fnichol/chef-apt'

cookbook 'nginx'
cookbook 'vim'