version: '3'
services:
  mongo:
    image: mongo:4.2
    ports:
    - 27017:27017

  web:
    platform: linux/amd64
    build: .
    volumes:
      - .:/tomatoes
    entrypoint: ./docker-entrypoint.sh
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - DO_HOST=mongo
